# Namespace where the Scylla Cluster will be created
apiVersion: v1
kind: Namespace
metadata:
  name: scylla-cql

---

# Role for scylla members.
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app: scylladb
  name: cql-cluster-member
  namespace: scylla-cql
rules:
  - apiGroups:
      - ''
    resources:
      - pods
    verbs:
      - get
  - apiGroups:
      - ''
    resources:
      - services
      - services/finalizers
    verbs:
      - get
      - list
      - patch
      - watch
      - update
  - apiGroups:
      - apps
    resources:
      - statefulsets
      - deployments/finalizers
      - statefulsets/finalizers
    verbs:
      - get
      - list
      - patch
      - watch
      - update
  - apiGroups:
      - scylla.scylladb.com
    resources:
      - scyllaclusters
      - scyllaclusters/finalizers
    verbs:
      - get
      - update
  - apiGroups:
      - security.openshift.io 
    resourceNames:
      - privileged
    resources:
      - securitycontextconstraints 
    verbs: 
      - use

---

# ServiceAccount for scylla members.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cql-cluster-member
  namespace: scylla-cql

---

# RoleBinding for scylla members.
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: scylladb
  name: cql-cluster-member
  namespace: scylla-cql
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cql-cluster-member
  namespace: scylla-cql
subjects:
  - kind: ServiceAccount
    name: cql-cluster-member
    namespace: scylla-cql

---

# Simple Scylla Cluster
apiVersion: scylla.scylladb.com/v1
kind: ScyllaCluster
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: cql-cluster
  namespace: scylla-cql
spec:
  version: 4.2.0
  agentVersion: 2.2.0
  developerMode: true
  datacenter:
    name: us-east-1
    racks:
      - name: us-east-1a
        scyllaConfig: "scylla-config"
        scyllaAgentConfig: "scylla-agent-config"
        members: 3
        storage:
          capacity: 5Gi
          storageClassName: rook-ceph-block
        resources:
          requests:
            cpu: 1
            memory: 1Gi
          limits:
            cpu: 1
            memory: 1Gi
